### PR TITLE
Changed the drive path

### PR DESCRIPTION
**Pull request by sadavarterohit**
The Google drive path in colab is not drive/My drive
It is drive/Mydrive
The space is not present, this recurring error has been rectified.

### CODE REVIEW

**Comment by chervonij** [comment]
@sadavarterohit 

well, something very strange.
I see that Colab has removed space from MyDrive.
but then why don't I have any errors?

**Comment by chervonij** [comment]
@sadavarterohit 
that's what I'm talking about.
import/export to Drive works for me even with this space. 
something strange is going on.

**Comment by chervonij** [comment]
or I can just not take the PR and just fix path to Drive with my commit

**Comment by sadavarterohit** [comment]
@chervonij 

Surprising how it doesn't work for me if it works for you. Strange indeed.

The view is different probably thanks to... well it being a notebook. 
So, although my notebook is likely to work anyway, feel free to do either of those things. 
I believe even your commit will have the same header file diffs, if you're cloning the repository again to make the changes.

**Pull request closed without merging**
