### PR TITLE
Wording/Phrasing changes, Remove References to multiple Drive accounts, Rename function name in Import Workspace, Refactor Dataset/Model Download

### PR DESCRIPTION
**Pull request by camjac251**
I saw after the change in Google Drive (same account restriction), that a reference to multiple Google accounts was in the text box, so I ended up removing it but then wanted to go further and try helping with some of the other stuff as well. I updated the GPUs that Colab has as well, filled out the VRAM amount for the GPUs I have gotten. I also changed the function name in "import workspace". Also refactored the dataset and model downloading to hopefully make it easier in the future for multiple options and also allow it to be optional and not required.

### CODE REVIEW

**Comment by chervonij** [comment]
@camjac251 

Okay, let's see.
1. Downloading datasets and Q96 model cannot be optional.
2. "GenericXSeg" and "Copy_to_Drive" must be enabled by default.
3. More detailed descriptions are helpful, but why so many "the"? Are you a native English speaker or are you using some kind of translator?

**Comment by camjac251** [comment]
I gave it another look and saw many mistakes that I originally missed. Sorry about that. Added a commit just now with the latest changes.

**Comment by chervonij** [comment]
@camjac251 

Okay, it works for you, but if someone needs to use built-in pretrain function and doesn't have CelebA or FFHQ downloaded, train won't start. Same for Quick96.

About language, that's fine, I'm just wondering )
I just often see google translator put "the" literally everywhere ))

**Comment by camjac251** [comment]
> @camjac251
> 
> if someone needs to use built-in pretrain function and doesn't have CelebA or FFHQ downloaded, train won't start. Same for Quick96.

The dropdown box for `Download_Dataset` and `Download_Pretrained_Model` help this. They're set at the default, None, since it'll be more convenient for someone to not have to set it to none every time they want to continue training vs having to change the option every time they load the window. If the dropdown is changed from None to say FFHQ, it'll download that during the installation process
image

**Comment by camjac251** [comment]
I noticed a typo I made with the CelebA dataset URL.  Fixed and should work now

**Comment by chervonij** [comment]
@camjac251 

> The dropdown box for Download_Dataset and Download_Pretrained_Model help this. 

I understand. That's not what I'm talking about.
I meant that you underestimate number of dumb people who will just forget to turn this option on, even when they need it. What to do with such people?

Now, pretrain dataset and Quick96 are loaded anyway. It's foolproof. It takes a few minutes, which isn't a lot of time on scale of a Colab session. Even if you save 5 minutes, on those options, it doesn't matter.

**Comment by camjac251** [comment]
The entire DFL workflow can be quite a feat of its own, but I guess I could come up with something, as I was hoping this could be merged for everyone to find use in. I was thinking of moving the Manage workspace block above the DFL Installation block since it's more convenient (In my opinion) to get all of the dialogue boxes out of the way if you're wanting to continue training but only have a minute.

I was thinking if someone did import their workspace before the install block would run, there could be a check to see if they have files in their `model` folder or `data_src`/`data_dst` folder and if nothing is detected, then it could run the download of both the dataset and model, regardless of the option above. 
I'll try and figure something else, but it might be more than what I was hoping for.

**Comment by chervonij** [comment]
@camjac251 

I understand what you want to do, but I have to consider that it will be used by different people, with different ideas of convenience and logic.

In any case. 
I disagree about optional uploading of datasets and Q96. 
Also, `GenericXSeg` must be enabled by default.

**Comment by chervonij** [comment]
Also, all sections must be collapsed by default

**Pull request closed without merging**
